### ISSUE TITLE
Case insensitive `key` and `value` tags

### ISSUE THREAD

**Issue by ArneMancofi** [albanian-xrm/PowerPlatform-Entity-Serializer#2]
In `AlbanianXrm.PowerPlatform.JsonConverters.AttributeCollectionConverter.Read(...)`, shouldn't the switch on the tag be case insensitive, for instance by replacing
```C#
switch (str)
{
  case "key":
    // ...
  case "value":
    // ...
}
```
with
```C#
switch (str.ToLowerInvariant())
{
  case "key":
    // ...
  case "value":
    // ...
}
```
?

**Comment by BetimBeja** [comment]
Hi @ArneMancofi,
in which case would the `key` and `value` be different than `LowerCase`?

I guess this "fix" wouldn't be a huge ask anyway. I will push this together with #1 as soon as we are ready.
